- name: Setup Nginx and Docker on the Server
  hosts: nginx
  become: yes
  tasks:
    - name: Ensure openssl and Docker are installed
      ansible.builtin.package:
        name: "{{ item }}"
        state: latest
      loop:
        - openssl
        - docker

    - name: Add current user to Docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        group: docker
        append: yes

    - name: Ensure Docker service is running
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: Create SSL directory for Nginx
      ansible.builtin.file:
        path: /etc/ssl/nginx
        state: directory
        mode: '0755'

    - name: Copy existing self-signed SSL certificate and key for miranda.com
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: '0644'
      loop:
        - { src: '../cert/miranda.com.crt', dest: '/etc/ssl/nginx/miranda.com.crt' }
        - { src: '../cert/miranda.com.key', dest: '/etc/ssl/nginx/miranda.com.key' }

    - name: Copy Nginx configuration to server
      ansible.builtin.copy:
        src: ./default.conf
        dest: /etc/nginx/conf.d/default.conf
        mode: '0644'

    - name: Pull the latest Nginx image
      community.docker.docker_image:
        name: nginx:alpine
        source: pull

    - name: Run Nginx container with self-signed SSL
      community.docker.docker_container:
        name: nginx
        image: nginx:alpine
        state: started
        restart_policy: always
        published_ports:
          - "443:443"
        volumes:
          - "/etc/ssl/nginx:/etc/ssl/nginx:ro"
          - "/etc/nginx/conf.d:/etc/nginx/conf.d:ro"
